@baseUrl = http://localhost:3333
# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "Lucas Trindade",
  "email": "lucas@thummi.global",
  "password": "123456"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "lucas@thummi.global",
  "password": "123456"
}